### ISSUE TITLE
Implement DecreaseKey / GetValue.

### ISSUE THREAD

**Issue by Quentin-M** [starwander/GoFibonacciHeap#1]
Your project seems to be the only recent / proper implementation of the Fibonacci Heap written in Go. I'd love to use it, however, some key features are missing. Off the top of my head, the most obvious one is `DecreaseKey` and another useful one would be a function that returns whether a Value is in the queue (maybe returning the item or nil,  and its priority maybe!) - but I am unsure if doable depending on the inner implementation.

**Comment by starwander** [comment]
Hi, thank you for your feedback! I'm just back from the vacation. Sorry for the delay reply.
I have implemented the DecreaseKey and several other API today. You can check the latest code now.

Please note that my implementation of Fibonacci Heap is a bit different from the transitional one. The main difference is that I add an index map into it to achieve better encapsulation of the golang interfaces. This will make the Union API to be O(n) running time instead of O(1). On the opposite, the random access is supported now which I think will satisfy your demand.

Please don't hesitate to let know if there is some bug or you have some other ideas.

**Comment by Quentin-M** [comment]
Awesome! I have a very similar implementation, only I don't have the index.

I believe that with the index, `DecreaseKey()` can be improved just a bit because thanks to the index, we can verify in O(1) that the element is present in the heap, therefore we don't actually need to call `resetMin()` but can simply compare the current minimum with the decreased node. Without the index, we can guarantee that the decreased node won't be inserted back into the heap if it wasn't there by setting every pop'd node's parent to nil - meaning that they won't be cut'd in, but we also need `resetMin()` instead of a simple comparison otherwise we may set it as the minimum of the heap while it's not actually in it. It should be possible to maintain a flag on the node to determine whether the node is still in the heap.

Also, the `Union()` might be problematic because when you call `heap.roots.PushBackList(anotherHeap.roots)`, Go makes a copy of the each `*list.Element` but not a copy of any `*node` of the heap, which means that both heaps will then share the same parent, marked, etc fields. Correct me if I'm wrong though. That's why I decided to not implement `Union()` at all on my implementation (and also because I don't need it at all I guess).

Feel free to close this issue!

**Comment by starwander** [comment]
Hi, several bugs is found during today's tests and review.
If you are use this code, please UPDATE to the latest version. Thank you!

I'm going to close this issue. Any feedback or discussion is welcomed to open a new one.
^o^
